version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=menu_project
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5431:5432'

  app:
    build: .
    ports:
      - '8000:8000'
    command: >
      sh -c 'python3 ./menu_project/manage.py migrate &&
      python3 ./menu_project/manage.py runserver 0.0.0.0:8000'
    depends_on:
    - db
  
volumes:
  pg_data:
    driver: local
