version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=menu_project
    ports:
      - '5431:5432'
      