# Generated by Django 4.2.7 on 2023-11-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_menuitem_menu_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_item',
        ),
    ]
